version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:

  BeforInstall:
    - location: scripts/check_and_deploy_app
      timeout: 300
      runas: root  
  AfterInstall:
    - location: scripts/up_server
      timeout: 300
      runas: root